site_name: Institute Knowledge Base
site_url: https://daniil-gv.github.io/FPMI_knowledgebase/

theme:
  name: material

docs_dir: vault
site_dir: site

nav:
  - Home: index.md
  - Areas:
      - Analysis: Areas/Analysis.md
  - Labs:
      - Lab PDE: Labs/Lab PDE.md
      - Lab ML: Labs/Lab ML.md
  - People:
      - Ivanov: People/Ivanov.md
      - Kim: People/Kim.md
  - Graph: graph.md